### PR TITLE
✨grammar✨nazi✨

### PR DESCRIPTION
**Pull request by ragasirtahk**

### CODE REVIEW

**Comment by albertonl** [comment]
no u

**Review by albertonl — APPROVED** [review]
good job bhai

**Review by MatejMecka — APPROVED** [review]
LGTM!

**Comment by shreyasminocha** [comment]
uwu what's dis

**Comment by albertonl** [comment]
uwu idk

**Comment by MatejMecka** [comment]
uwu this is an Open Source contribution

**Comment by albertonl** [comment]
uwu i like having my contribution graph green

**Comment by albertonl** [comment]
uwu haha matej email go brrrrrr

**Comment by MatejMecka** [comment]
uwu notifications waking me up go brrrr brrrrr

**Comment by ragasirtahk** [comment]
gud job everyone uwu

**Comment by shreyasminocha** [comment]
uwu waking up to several notif emails

**Comment by albertonl** [comment]
uwu my phone is always silent

**Comment by albertonl** [comment]
uwu right @MatejMecka ?

**Comment by MatejMecka** [comment]
UwU @albertonl mentioned you in a pull request

**Comment by albertonl** [comment]
uwu @MatejMecka idk

**Comment by MatejMecka** [comment]
UwU this is a bit weird isn't it?

**Comment by shreyasminocha** [comment]
UwU shut up

**Comment by ragasirtahk** [comment]
pls forgive my notifs uwu

**Comment by albertonl** [comment]
uwu we're making of the world a better place thanks to our open source so no one shuts up uwu

**Comment by shreyasminocha** [comment]
meme man going "tehc"

's/tehc/upen sores'

**Comment by albertonl** [comment]
uwu

**Comment by ragasirtahk** [comment]
can we please stop now uwu

**Comment by MatejMecka** [comment]
UwU you have a new notification

**Comment by albertonl** [comment]
uwu no one stops uwu

**Comment by albertonl** [comment]
uwu?

**Comment by shreyasminocha** [comment]
GH unsubscribe button being clicked

bye.

**Comment by albertonl** [comment]
uwu rip @shreyasminocha

**Pull request merged**
